### ISSUE TITLE
Contact list - simultaneous actions on multiple contacts

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#14]
In contact list, as a user I would like to edit or delete multiple contacts at once by marking the contacts individually and then choose an action (delete or edit)

**Comment by chrberndt** [comment]
I understand, that deleting multiple contacts at once is a useful feature. But would "edit multiple contacts" mean?

**Comment by KaiDol** [comment]
it would be nice for adding or editing single or multiple tags on contacts.

in a more advanced version it would be nice to edit multiple address data like cities, countries, even companies. But this is nothing for Flussbad since we edit contacts in FM.

**Comment by chrberndt** [comment]
We have implemented a first set of set-operations: delete selected contacts and download selected contacts as vcards. I will therefore close this issue and create new issues for the suggested set editing of records and the application of tags / categories.
