### ISSUE TITLE
Contact View panel Tags: not all tags are shown

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#19]
Only the first line of categories are shown, although all categories (i.g. tags) are searchable, it would be nice to have all the others shown in the view pane of every contact.
I put an example of different Category types and lines below:

<pre>CATEGORIES;PREF=1;TYPE=Mitgliedsstatus:Unterstützer,Interessent
CATEGORIES;PREF=2;TYPE=Verteiler:Presse</pre>

**Comment by chrberndt** [comment]
I'm not sure whether that's a bug or whether there is something wrong with the import data. When there is only line of categories, we have read them in this form from the import. (e.g. Hendrik Pupat, Brigitte Preissler). (You can check the vCard in raw-format in the respective tab.)

If there are in fact two category sections (e.g. Christian Berndt) they are displayed in two rows with their respective section label.

**Comment by chrberndt** [comment]
Hi Kai, 

if you can confirm, that the issue has been solved, could you please close the issue?

Thanks in advance, 

Christian
