### ISSUE TITLE
Prev Email not shown in contact list

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#22]
In Contact list only first email address of vcard file is listed, but it should be the preferred one, as stated in vcard file. 
from the example below only the second address should be listed in contact list.

<pre>EMAIL;TYPE=INTERNET,WORK:1st_adress@in_vcard_fi.le
EMAIL;TYPE=INTERNET,HOME;PREF=1:2nd_and_preferred_adress@in_vcard_fi.le
EMAIL;TYPE=INTERNET,HOME:3rd_adress@in_vcard_fi.le</pre>

**Comment by chrberndt** [comment]
You're right: we silently assumed that the records are stored in the order of their preference which is not correct. We will fix this in the next Snapshot.

**Comment by chrberndt** [comment]
The issue is fixed, both for the EMAIL and for the TEL and deployed with 0.5.0-SNAPSHOT
