### ISSUE TITLE
Bug: Contact Link whenLinked asset not working

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#28]
When I am in a memo with linked contacts I am not forwarded to the contact's page when I click on the contact's link. I stay within the memo. Please fix.

**Comment by chrberndt** [comment]
We can reproduce the issue and will deploy a fixed version today.

**Comment by chrberndt** [comment]
The issue has been fixed and the fix is already deployed with 0.6.2-SNAPSHOT. Both, to dev and portal.flussbad-berlin.de .
