### ISSUE TITLE
Request: Change Field for headline in List of Stories

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#30]
For the List of all stories please use "Überschrift" as headline and not "Titel"

<img width="852" alt="bildschirmfoto 2015-09-17 um 07 56 38" src="https://cloud.githubusercontent.com/assets/6461005/9926045/1c8be9d6-5d12-11e5-89d4-7fcb965856f3.png">

**Comment by chrberndt** [comment]
Hi Kai, 

the feature was already in the pipeline. It's now implemented and already deployed. See: 

http://neu.flussbad-berlin.de/logbuch

Best, 

Christian
