### ISSUE TITLE
Contact Update after import not working

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#4]
When importing a vcard file that has been already imported before, a new contact is generated instead of the existing contact only updated.
I check UID of both contacts: it is the same...

**Comment by chrberndt** [comment]
Hi Kai,

could you please check the field label for the uid in your import? At least in the contacts exported from dev.flussbad I find entries with "X-ABUID:08AE66AE-1512-45BD-96DA-78140227E323" or similar, but not with UID as defined in the specs: https://tools.ietf.org/html/rfc6350#page-46. 

At the moment we dont care about the internal format (URI or not) as long as the UID value is unique but in future releases we might handle this more strict.

Best Christian

**Comment by chrberndt** [comment]
Since version 0.1.0-SNAPSHOT you can choose to overwrite existing records with your imported data.

**Comment by KaiDol** [comment]
OK that was the issue. Thanks
